### ISSUE TITLE
Tetrys

### ISSUE THREAD

**Issue by wangxuanda** [elochin/elochin.github.io#1]
Hello, professor Emmanuel Lochin. 
I am studying in sliding window coding and I found that your Tetrys algorithm is pretty good. However, I found the source code "speeryt" on your homepage is not available. Can you send me the Tetrys source code to my email? My email is 731790119@qq.com.
Thanks a lot!

**Comment by elochin** [comment]
Tetrys library is currently under commercial license. If you want an overview on how is implemented such library, you can refer to this project : https://github.com/irtf-nwcrg/swif-codec where a sliding window FEC has been implemented during the IRTF/NWCRG hackathon. Or you can refer to this simulation demo code : https://github.com/yeliqseu/streamc where the authors explained in their paper (https://ieeexplore.ieee.org/document/9075270) how they implemented a Tetrys-like codec.

**Comment by elochin** [comment]
Tetrys library is currently under commercial license. If you want to have an overview on how is implemented such library, you can refer to this project : https://github.com/irtf-nwcrg/swif-codec where a sliding window FEC has been implemented during the IRTF/NWCRG hackathon. Or you can refer to this simulation demo code : https://github.com/yeliqseu/streamc where the authors explained in their paper (https://ieeexplore.ieee.org/document/9075270) how they implemented a Tetrys-like codec.

**Comment by wangxuanda** [comment]
I see. Thank you for your help.





---Original---
From: "Emmanuel ***@***.***&gt;
Date: Fri, Mar 25, 2022 13:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [elochin/elochin.github.io] Tetrys (Issue #1)




 
Tetrys library is currently under commercial license. If you want to have an overview on how is implemented such library, you can refer to this project : https://github.com/irtf-nwcrg/swif-codec where a sliding window FEC has been implemented during the IRTF/NWCRG hackathon. Or you can refer to this simulation demo code : https://github.com/yeliqseu/streamc where the authors explained in their paper (https://ieeexplore.ieee.org/document/9075270) how they implemented a Tetrys-like codec.
